# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Precio',
            new_name='precio',
        ),
    ]
